# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_sitepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserverping',
            name='version',
            field=models.CharField(default='1.11.1', max_length=16, verbose_name=b'Minecraft version'),
            preserve_default=False,
        ),
    ]
